// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityPackSummary } from "./CapabilityPackSummary";
import type { MemoryPolicy } from "./MemoryPolicy";
import type { PermissionPolicy } from "./PermissionPolicy";
import type { RoleKind } from "./RoleKind";

export type AgentDefinitionSummary = { id: string, roleTemplateId: string, roleKind: RoleKind, slug: string, name: string, description: string, instructions: string, responsibilities: Array<string>, nonResponsibilities: Array<string>, inputContract: unknown, resultContract: unknown, qualityRubric: unknown, defaultEngineKind: string, defaultModelConfigurationId: string | null, defaultPermissionPolicy: PermissionPolicy, defaultParallelism: number, memoryPolicy: MemoryPolicy, capabilityPacks: Array<CapabilityPackSummary>, builtin: boolean, active: boolean, version: number, createdAt: string, updatedAt: string, };
