// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSessionStatus } from "./AgentSessionStatus";

export type AgentSessionSummary = { id: string, workId: string, agentInstanceId: string, engineKind: string, generation: number, engineSessionId: string | null, currentAssignmentId: string | null, lastSuccessfulTurnId: string | null, rotationReason: string | null, status: AgentSessionStatus, createdAt: string, updatedAt: string, invalidatedAt: string | null, };
