// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDefinitionSummary } from "./AgentDefinitionSummary";
import type { AgentStatus } from "./AgentStatus";
import type { PermissionPolicy } from "./PermissionPolicy";

export type AgentInstanceSummary = { id: string, definition: AgentDefinitionSummary, displayName: string, engineOverride: string | null, modelConfigurationOverride: string | null, permissionPolicyOverride: PermissionPolicy | null, parallelismOverride: bigint | null, builtin: boolean, status: AgentStatus, createdAt: string, updatedAt: string, };
