// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssemblyDiagnosticCode = "not_executable" | "incompatible_role" | "missing_tool" | "missing_engine_capability" | "permission_escalation" | "capability_conflict" | "context_budget_exceeded";
