// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentKind } from "./AssignmentKind";
import type { AssignmentSideEffect } from "./AssignmentSideEffect";
import type { AssignmentStatus } from "./AssignmentStatus";

export type AssignmentSummary = { id: string, workId: string, parentAssignmentId: string | null, createdByAgentId: string | null, assignedAgentId: string, capabilityPackId: string | null, kind: AssignmentKind, sideEffect: AssignmentSideEffect, title: string, instruction: string, contextManifest: unknown, expectedResultSchema: unknown, acceptanceCriteria: unknown, permissionScope: unknown, priority: number, status: AssignmentStatus, attemptCount: number, maxAttempts: number, notBefore: string | null, resultSummary: string | null, lastError: string | null, nextAttemptAt: string | null, recoveryReason: string | null, createdAt: string, claimedAt: string | null, startedAt: string | null, completedAt: string | null, updatedAt: string, };
