// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssignmentStatus = "queued" | "claimed" | "running" | "waiting" | "completed" | "failed" | "cancelled" | "interrupted" | "dead_letter" | "recovery_confirmation_required";
