// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssignmentSideEffect = "read_only" | "idempotent_write" | "non_idempotent_write" | "unknown";
