// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityPackStatus } from "./CapabilityPackStatus";
import type { PermissionPolicy } from "./PermissionPolicy";

export type CapabilityPackSummary = { id: string, catalogCapabilityId: string | null, name: string, description: string, instructions: string, inputSchema: unknown, outputSchema: unknown, procedure: unknown, validationRubric: unknown, requiredTools: Array<string>, defaultPermissionScope: PermissionPolicy, compatibleRoleTemplateIds: Array<string>, requiredEngineCapabilities: Array<string>, conflictsWithCapabilityPackIds: Array<string>, version: number, status: CapabilityPackStatus, };
