// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompleteWorkDeliveryInput = { summary: string, artifacts: Array<string>, validation: Array<string>, limitations: Array<string>, };
