// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type CreateWorkInput = { title: string, goal: string, rootPath: string, permissionMode: PermissionMode, resourceDraftId: string | null, };
