// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelegateAssignmentInput = { assignedAgentId: string, capabilityPackId: string | null, title: string, instruction: string, contextManifest: unknown, expectedResultSchema: unknown, acceptanceCriteria: unknown, permissionScope: unknown, priority: number, maxAttempts: number, };
