// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompleteWorkDeliveryInput } from "./CompleteWorkDeliveryInput";
import type { DelegateAssignmentInput } from "./DelegateAssignmentInput";
import type { RecordWorkDecisionInput } from "./RecordWorkDecisionInput";
import type { RequestClarificationInput } from "./RequestClarificationInput";
import type { SubmitAssignmentResultInput } from "./SubmitAssignmentResultInput";
import type { UpdateWorkPlanInput } from "./UpdateWorkPlanInput";

export type HostToolCall = { "tool": "listWorkMembers" } | { "tool": "inspectCapabilityPacks", ids: Array<string>, } | { "tool": "delegateAssignment" } & DelegateAssignmentInput | { "tool": "getAssignmentStatus", assignmentIds: Array<string>, } | { "tool": "cancelAssignment", assignmentId: string, } | { "tool": "requestAssignmentRetry", assignmentId: string, } | { "tool": "recordWorkDecision" } & RecordWorkDecisionInput | { "tool": "updateWorkPlan" } & UpdateWorkPlanInput | { "tool": "completeWorkDelivery" } & CompleteWorkDeliveryInput | { "tool": "submitAssignmentResult" } & SubmitAssignmentResultInput | { "tool": "requestClarification" } & RequestClarificationInput;
