// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerPlanStepStatus } from "./LedgerPlanStepStatus";

export type LedgerPlanStep = { id: string, title: string, status: LedgerPlanStepStatus, };
