// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryCandidateStatus } from "./MemoryCandidateStatus";

export type MemoryCandidateSummary = { id: string, sourceWorkId: string, sourceEventId?: string, authorAgentId: string, content: string, reason: string, version: number, status: MemoryCandidateStatus, createdAt: string, resolvedAt?: string, resolvedBy?: string, };
