// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueueControlMode = "enqueue_next" | "steer_current" | "interrupt_and_replace";
