// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResultValidation = { command: string, success: boolean, summary: string, authorAgentId: string, assignmentId: string, occurredAt?: string, };
