// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DelegationRequest } from "./DelegationRequest";
import type { MemoryCandidateInput } from "./MemoryCandidateInput";
import type { ResultArtifact } from "./ResultArtifact";
import type { ResultEvidence } from "./ResultEvidence";
import type { ResultFinding } from "./ResultFinding";
import type { ResultStatus } from "./ResultStatus";
import type { ResultValidation } from "./ResultValidation";

export type ResultEnvelope = { status: ResultStatus, summary: string, findings: Array<ResultFinding>, evidence: Array<ResultEvidence>, artifacts: Array<ResultArtifact>, validation: Array<ResultValidation>, decisionsRecommended: Array<string>, uncertainties: Array<string>, delegationRequests: Array<DelegationRequest>, memoryCandidates: Array<MemoryCandidateInput>, limitations: Array<string>, extensions: Record<string, unknown>, };
