// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResultFinding = { title: string, detail: string, confidence: string | null, sourceEventId?: string, authorAgentId: string, assignmentId: string, occurredAt?: string, };
