// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResultEvidence = { description: string, sourceEventId?: string, sourceResourceId?: string, sourcePath?: string, authorAgentId: string, assignmentId: string, occurredAt?: string, };
