// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleKind } from "./RoleKind";

export type RoleTemplateSummary = { id: string, slug: string, roleKind: RoleKind, name: string, description: string, baseInstructions: string, responsibilities: Array<string>, nonResponsibilities: Array<string>, baseResultContract: unknown, compatibleCapabilityKinds: Array<string>, builtin: boolean, version: number, createdAt: string, updatedAt: string, };
