// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";

export type RunSummary = { id: string, workId: string, engineKind: string, engineSessionId: string | null, modelLabel: string, status: RunStatus, createdAt: string, startedAt: string | null, completedAt: string | null, };
