// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeCheck } from "./RuntimeCheck";

export type RuntimeStatus = { python: RuntimeCheck, node: RuntimeCheck, git: RuntimeCheck, };
