// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSummary } from "./MessageSummary";
import type { RunSummary } from "./RunSummary";

export type StartWorkOutput = { run: RunSummary, userMessage: MessageSummary, };
