// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentSummary } from "./AssignmentSummary";
import type { RunSummary } from "./RunSummary";
import type { UserMessageSummary } from "./UserMessageSummary";

export type StartWorkOutput = { assignment: AssignmentSummary, run: RunSummary | null, userMessage: UserMessageSummary, };
