// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRole } from "./MessageRole";

export type UserMessageSummary = { id: string, workId: string, assignmentId?: string, runId?: string, role: MessageRole, content: string, resourceIds: Array<string>, createdAt: string, };
