// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSummary } from "./MessageSummary";
import type { RunSummary } from "./RunSummary";
import type { WorkEventEnvelope } from "./WorkEventEnvelope";
import type { WorkSummary } from "./WorkSummary";

export type WorkDetail = { summary: WorkSummary, runs: Array<RunSummary>, messages: Array<MessageSummary>, events: Array<WorkEventEnvelope>, };
