// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkEventPayload } from "./WorkEventPayload";

export type WorkEventEnvelope = { version: number, eventId?: string, workId: string, runId: string, turnId?: string, sessionId?: string, agentId?: string, assignmentId?: string, causationId?: string, correlationId?: string, sequence: number, occurredAt: string, payload: WorkEventPayload, };
