// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkAgentSummary } from "./WorkAgentSummary";

export type WorkTeamSummary = { workId: string, lead: WorkAgentSummary, members: Array<WorkAgentSummary>, };
