// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerDecision } from "./LedgerDecision";
import type { LedgerPlanStep } from "./LedgerPlanStep";

export type WorkLedger = { goal: string, plan: Array<LedgerPlanStep>, decisions: Array<LedgerDecision>, constraints: Array<string>, permissions: Array<string>, activeAssignments: Array<string>, waitingAssignments: Array<string>, completedAssignments: Array<string>, artifacts: Array<string>, validation: Array<string>, openQuestions: Array<string>, lastDelivery?: string, };
