// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInstanceSummary } from "./AgentInstanceSummary";
import type { PermissionPolicy } from "./PermissionPolicy";
import type { RoleKind } from "./RoleKind";
import type { WorkAgentStatus } from "./WorkAgentStatus";

export type WorkAgentSummary = { workId: string, instance: AgentInstanceSummary, roleKind: RoleKind, status: WorkAgentStatus, permissionPolicy: PermissionPolicy, joinedAt: string, updatedAt: string, };
