// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";
import type { WorkStatus } from "./WorkStatus";

export type WorkSummary = { id: string, title: string, goal: string, rootPath: string, permissionMode: PermissionMode, status: WorkStatus, createdAt: string, updatedAt: string, };
